Fixing stylelint install that cause exception during build.
 ERROR in ./node_modules/css-loader?{"importLoader":true,"minimize":true,"sourceMap":true}!./node_modules/sass-loader/lib/loader.js?{}!./node_modules/postcss-loader/lib!./src/app/app.scss
    Module build failed: Error: Cannot find module 'table'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (angularjs-es6-starter-kit\node_modules\stylelint\lib\formatters\stringFormatter.js:3:15)